version: '3.8'

services:
  db:
    image: mysql:8.0
    ports:
      - "8070:3306"
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: note
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      - my_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: user
      PMA_PASSWORD: password
    depends_on:
      - db
    networks:
      - my_network
networks:
  my_network:
    driver: bridge
